### ISSUE TITLE
Fatal error: Call to undefined function azera_shop_companion_sevices_get_default_content() 

### ISSUE THREAD

**Issue by Hirmuinen** [Codeinwp/azera-shop-companion#21]
Fatal error: Call to undefined function azera_shop_companion_sevices_get_default_content() in /www/htdocs/.../.../wp-content/plugins/azera-shop-companion/inc/settings.php on line 55

So I can't use the customizer anymore, any idea how to fix this?

**Comment by rodica-andronache** [comment]
Hi @Hirmuinen,

Are you using the latest versions of both Azera Shop theme and Azera Shop Companion plugin?
Please let me know.

Regards,
Rodica

**Comment by Hirmuinen** [comment]
Hei. I'm using the latest version of the Azera Shop Companion plugin and Version: 1.1.5 of Azera Shop theme. Everything was working okie, until I made changes in the customizer in one of the companion sections. While saving the page crashed (saving sign never stopped) and afterwards there was the FATAL ERROR.

Thanks & BR,
Harald

**Comment by rodica-andronache** [comment]
Hi @Hirmuinen,

The latest version of Azera Shop is 1.1.10 so you should use that.
It's possible you entered an incorrect value in the customizer, causing some errors maybe. 
If you need help on this, the best way would be to contact us here https://themeisle.com/contact/ so we can get more details.

Thank you,
Rodica

**Comment by Hirmuinen** [comment]
Hei. Made the update and it works again, but had to make changes on the theme again, thats why I wanted to avoid that. Do you know, if child themes are working with 1.1.10 and the Companion plugin now? Cause under 1.1.5 it wasn't.

Thanks  a lot!

**Comment by rodica-andronache** [comment]
Hi @Hirmuinen,

It should work. It also depends on how you create your child theme.

Regards,
Rodica
