### ISSUE TITLE
Banner and icon images

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/azera-shop-companion#3]
after the plugin is live on wp.org

**Comment by rodica-andronache** [comment]
@abaicus the plugin is live https://wordpress.org/plugins/azera-shop-companion/

**Comment by abaicus** [comment]
![icon2](https://cloud.githubusercontent.com/assets/15010186/14633459/56ff4dca-0626-11e6-92f4-331c2e77c46b.png)
![banner-772x250](https://cloud.githubusercontent.com/assets/15010186/14633460/571c1ec8-0626-11e6-9bd1-dcd32bffb188.png)

**Comment by rodica-andronache** [comment]
Thanks :) I added the images on wp.org
